# Generated by Django 3.1.6 on 2021-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
